apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-kube-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jay-patel21/ms.git
    targetRevision: main
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: node-kube-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

