apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: node-kube-prod
  labels:
    app: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: us-central1-docker.pkg.dev/genuine-wording-474900-e7/node-kube-repo/node-kube-app:service-b-a67182dfe41740fddb89817c04bcf8f2135e898a
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: '3000'
        - name: PEER_SERVICE_NAME
          value: service-b-internal
        - name: PEER_SERVICE_PORT
          value: '3000'
        - name: ENVIRONMENT
          value: production
        envFrom:
        - configMapRef:
            name: service-b-config
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
