apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: node-kube-prod
  labels:
    app: service-b
spec:
  type: ClusterIP
  selector:
    app: service-b
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP

